name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Install net6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install net7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Install net8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Install net9.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'
      - name: Run ./build.sh Coverage
        run: ./build.sh Coverage
        env:
          NugetApiKey: ${{ secrets.NUGET_API_KEY }}
      - name: Upload Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: artifacts/coverage-report