name: Publish pre-release NuGet packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install net8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install net9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install net10.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Pack and publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: make publish
