name: Publish pre-release NuGet packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Install net6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install net7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Install net8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Run NugetPublish
        run: ./build.sh publish
        env:
          NugetApiKey: ${{ secrets.NUGET_API_KEY }}
